os: Visual Studio 2015

environment:
  ARTIFACT_FILE: "Win32.zip"
  API_KEY:
    secure: oCRAOcipgzMe9tum/tZx7vXbV1k/5Q9sD/pbcmlGbDbHCPkkPnswxYRq0cAhNF19

branches:
  only:
    - /^v.*$/

build: off

install:
  - chocolatey install wget
  - chocolatey install jq
  - C:\cygwin\bin\bash "bin/copy"
  - C:\cygwin\bin\bash "bin/build"
  - C:\cygwin\bin\bash "bin/preflight" "validate"
  - C:\cygwin\bin\bash "bin/release"
